Policy to manage aspects of the =apt= package manager.

** Modules

*** apt-pin-packages
- *Bundle* - =apt:pin_packages=

This module handles managing package pin configurations for a set of packages. It leverages =library-apt-pin-package-version-priority=. Its primarily configured by the variable =apt:pin_packages.config=. This module is designed to integrate well with CFEngine Build module inputs, group data, and host specific data in CFEngine Enterprise Mission Portal.

*** library-apt-pin-package-version-priority
- *Bundle* - =apt:package_version_priority_pinned(name, version, priority, state)=
- =name= - The name of the package.
- =version= - The version of the package to pin.
- =priority= - The priority of the package pin.
- =state= - The desired configuration state of the pin. The value should be =present= or =absent=.

#+begin_src cfengine3 :exports code
bundle agent example
{
  methods:
      "Ensure apt package is pinned to version"
        usebundle => apt:package_version_priority_pinned( "zpackage",
                                                          "1.2.3",
                                                          "999",
                                                          "present" );
  }
#+end_src

** Variables
- =apt:package_version_priority_pinned.preferences_dir= - String setting the directory where configuration files for apt package pinning should be managed. Defaults to =/etc/apt/preferences.d/=. This is primarily used for testing so that the target system is unaffected.
  #+begin_src json
    {
        "variables": {
            "apt:package_version_priority_pinned.preferences_dir": {
                "value": "$(sys.policy_entry_dirname)/artifacts"
            }
        }
    }
  #+end_src
- =apt:pin_packages.config= - Data container of objects keyed by the package name with =version=, =priority=, and =state= keys.
  #+begin_src json
    {
        "variables": {
            "apt:pin_packages.config": {
                "value": {
                    "zpackage": {
                        "version": "1.2.3",
                        "priority": "999",
                        "state": "present"
                    },
                    "apackage": {
                        "version": "0",
                        "priority": "0",
                        "state": "absent"
                    }
                }
            }
        }
    }
  #+end_src
